### ISSUE TITLE
module "fancy-mini/lib/wepyKit" is not defined

### ISSUE THREAD

**Issue by zhang14725804** [zhuanzhuanfe/fancy-mini#3]
非wepy项目引入“”无限层级路由方案“”

VM24379:1 thirdScriptError 
 sdk uncaught third Error 
 module "fancy-mini/lib/wepyKit" is not defined 
 Error: module "fancy-mini/lib/wepyKit" is not defined

但是我看项目目录下存在wepyKit.js文件，请问是什么原因呢

**Comment by bluesky12** [comment]
看报错信息，应该是把"fancy-mini/lib/wepyKit"整个当成包名了，但实际应该是"fancy-mini"包的"/lib/wepyKit"目录
建议检查下你们的项目是否支持引用npm包的子文件，一般应该是支持的；确实不支持的话，可以手动拷贝到项目目录中使用
