### ISSUE TITLE
免并发修饰器 如何使用

### ISSUE THREAD

**Issue by fantingsheng** [zhuanzhuanfe/fancy-mini#4]
这个免并发修饰器如何使用，有相应的例子么

**Comment by bluesky12** [comment]
noConcurrent修饰器使用示例：https://github.com/zhuanzhuanfe/fancy-mini-demos/blob/master/src/pages/noConcurrent/components/NoConcurrent.wpy
其它修饰器使用方式类似，会陆续补充
