### ISSUE TITLE
修饰器 放在类名和方法上是没什么问题的，放在里面就报错

### ISSUE THREAD

**Issue by whoyouni** [zhuanzhuanfe/fancy-mini#6]
![image](https://user-images.githubusercontent.com/15389683/53148292-32593200-35e5-11e9-8449-908c2984a6e1.png)

**Comment by Lionad-Morotar** [comment]
装饰器不是只能放在类方法和lei'shuxing类属性里面的么~~

**Comment by bluesky12** [comment]
修饰器语法目前处于提案阶段，还没有定案。使用细节跟具体的编译环境有关。
在fancy-mini的编译环境中（es6+babel），修饰器是可以用于普通对象的；
在另一些环境（比如：ts）中，修饰器就不能用在普通对象上，却可以用在函数的参数上。

另外，根据这个提案：https://github.com/tc39/proposal-decorators 修饰器语法最终定案很可能会跟现在长得完全不一样。

**Comment by bluesky12** [comment]
最近重构了一版，没有在对象上使用修饰器了；逻辑也拆解出来，可以直接使用了。
有兴趣的话可以再扫一眼：
文档：https://zhuanzhuanfe.github.io/fancy-mini/tutorial-2.1-login.html
源码：https://github.com/zhuanzhuanfe/fancy-mini/blob/master/src/login/BaseLogin.js
