### ISSUE TITLE
登录模块 耦合太多了

### ISSUE THREAD

**Issue by yanhaidao-bjhl** [zhuanzhuanfe/fancy-mini#7]
登录模块 耦合太多了，有具体计划优化吗

**Comment by abrahamgreyson** [comment]
+1

**Comment by bluesky12** [comment]
最近重构了一版，有兴趣的话可以再扫一眼：
文档：https://zhuanzhuanfe.github.io/fancy-mini/tutorial-2.1-login.html
源码：https://github.com/zhuanzhuanfe/fancy-mini/blob/master/src/login/BaseLogin.js

**Comment by WuJiY** [comment]
登录模块 耦合还是太多 能单独分开几个模块吗，段位低不知道怎么用U+1F602
