### ISSUE TITLE
@tap 与getuserinfo点击事件冲突

### ISSUE THREAD

**Issue by yanhaidao-bjhl** [zhuanzhuanfe/fancy-mini#8]
https://github.com/zhuanzhuanfe/fancy-mini/blob/master/components/DialogCommon.wpy

小程序调试库：2.6.5
导致无法获取到用户信息

**Comment by bluesky12** [comment]
试了下可以正常获取到用户信息，问题没有复现。  

演示小程序fancyDemos上有使用示例，你试下：
1. 扫码进入演示小程序fancyDemos  
![image](https://user-images.githubusercontent.com/10047420/56081204-509d1a80-5e3d-11e9-95a0-18e7859cb691.png)
2. 点击上方'console'按钮打开调试开关方便查看控制台日志
3. 往下滑，点击“通用弹窗”卡片->点击“获取手机号、Promise”->点击“立即绑定”->同意授权，查看控制台日志，应该能看到类似如下输出：  
![image](https://user-images.githubusercontent.com/10047420/56081255-cdc88f80-5e3d-11e9-8b05-356478189a33.png)  

如果你手机上也正常的话，应该就是调用方式的问题了，可以参考演示小程序的源码[fancy-mini-demos](https://github.com/zhuanzhuanfe/fancy-mini-demos)
